### ISSUE TITLE
Do we want a file browser with inline messages ?

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala-html#16]
In my opinion we should have:

 - `Results` tab which shows the Results in the current format.
 - `Files` tab which shows a list of files with some stats on the side (Number of results and which bears ran on them) and each file can open with inline results

I personally like the `Files` tab more - because I find it more user friendly.

**Comment by AbdealiJK** [comment]
There can also be a tab for LogMessages (for https://github.com/coala-analyzer/coala-html/issues/15)

**Comment by sils1297** [comment]
yeah would be neat to turn the files tab into some cool way to view results :)

**Comment by AbdealiJK** [comment]
So, in the above commits I've added a simple file browser. Adding results to it is not that simple - as currently google-code-prettifier handles the display. We need to hook into it and show comments on the side somehow
