### ISSUE TITLE
Make coala-html into a bower package

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala-html#23]
We should make this a bower package and let the `coala-html` binary check if the bower package is installed (somehow)

**Comment by sils1297** [comment]
ah then you just have the index.html, a bower config, the json data and thats it, right?

**Comment by sils1297** [comment]
though bower doesn't install stuff system wide anyway so we can simply check if the folder is there in the right place or just run bower update automatically, bower will only do updates as needed then

**Comment by tushar-rishav** [comment]
Closing in favor of https://github.com/coala-analyzer/coala-html/issues/43
