### ISSUE TITLE
Add testing framework

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala-html#24]
Until now although travis is enabled we do not use unittests.

We need to decide on which framework to use and to also set it up.

**Comment by AbdealiJK** [comment]
So, this is something I'm not very familiar with.

Selenium is a popular library which uses a browser and you can click on things and see what happens to the browser screen. Not sure if it works in travis or whether it needs XDisplay (I remember dogtail has issues when doing i for coala-gui)

For simple angular unittests karma and mocha are two names Ive seen commonly. Maybe use them ?

@tushar-rishav opinions ?

**Comment by tushar-rishav** [comment]
@AbdealiJK 

- I'm familiar with Selenium but ain't sure about it's integration with travis. I think if we want headless testing then PhantomJS might be useful? Travis env provides PhantomJS. 

-  Karma or Jasmine seems to be promising.  We can use them.

**Comment by sils1297** [comment]
FWIW there's a PhantomJS webdriver for selenium

Sincerely,

Lasse Schuirmann

contact@viperdev.io
http://viperdev.io/

2016-02-28 13:28 GMT+01:00 Tushar <notifications@github.com>:
