### ISSUE TITLE
Add unittests for code

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala-html#25]
Add unittests for all our code and make sure coverage is 100%

Blocked by https://github.com/coala-analyzer/coala-html/issues/24

**Comment by AbdealiJK** [comment]
This is sort of blocked - because we are hardcoding the "simple" project inside the controllers. We cannot test the controllers properly because of this. We need to figure out how the html binary will be injecting the project's path into the angular stuff.
Ideas ?

**Comment by tushar-rishav** [comment]
@AbdealiJK Shall we close this now?
