### ISSUE TITLE
Show all affected source ranges in Results

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala-html#28]
Currently we only show the first.

**Comment by Nosferatul** [comment]
I would like to work on this !

**Comment by Adrianzatreanu** [comment]
glad to hear this, i have assigned you.

**Comment by AbdealiJK** [comment]
So the way this would work is that we need an extra `ng-repeat` which will show all the source ranges inside a result.
We need to change the data given in `main.js` (Currently we only give the first item) to the template and then change the template with ng-repeat too.
Finally we also need to modify test_projects/simple to get a demo working (currently all results there only have a single range)

**Comment by Nosferatul** [comment]
So i have to change index.html and add ng-repeat, and main.js should receive all the data? ive read here https://docs.angularjs.org/api/ng/directive/ngRepeat also, i dont really know how to create that demo..

**Comment by tushar-rishav** [comment]
@AbdealiJK Probably we won't need to change anything in views. We might just need to change main.js such that we pass all the source ranges. Something like
```javascript
el.affected_code.forEach(function( sourceRange ){...}
``` 
and rest being same. IMO that'd suffice

**Comment by AbdealiJK** [comment]
@tushar-rishav personally, I like working in views for something like this.
I prefer to just push the whole json dump from coala-json to the view and show it appropriately here.
I find it double work to restructure json and then send it to the view for the layout part. As we're mixing up layout templates and frontend logic.

But these are just my "views" ( pun intended XD ) ... I think you should take the call on what you like more.
