### ISSUE TITLE
coala html binary

### ISSUE THREAD

**Issue by tushar-rishav** [coala-analyzer/coala-html#31]
_From @AbdealiJK on February 28, 2016 5:57_

So, as I see it the coala html binary needs to do three things:

Install coala-html angular app via bower. Also install the bower dependencies.

- [x]  run coala and dump the results in json format to a particular file if it doesn't exists else update it. This file shall be used by Angular app.

- [x] create `file.json` if it doesn't exists else update it.

- [x] Finally, create a server and open the file. This can have some flexibility. User can decide whether to launch the webpage immediately after running coala-html or maybe just update/create the files.

Fixes https://github.com/coala-analyzer/coala-html/issues/31

We probably want an arg to just create the server / open the last result too.

_Copied from original issue: coala-analyzer/coala#1733_

**Comment by tushar-rishav** [comment]
@AbdealiJK 

-  We might want to add an option that allows users to switch between the output from predefined location or run `coala-json` and update the output. 

-  Yes we should create a `file.json` the first time we run coala-json.

-  [Webbrowser](https://docs.python.org/3.1/library/webbrowser.html) is what we might need.

**Comment by AbdealiJK** [comment]
@tushar-rishav I agree with everything you mentioned in the comment.
And Im wondering why this was moved to coala-html repo. I thought the python coala-html binary can reside in `coala` and only the bower package can reside in `coala-html`. `coala` uses the bower package `coala-html` and renders the html thing

**Comment by AbdealiJK** [comment]
I dind't want to add python setup.py and stuff here

**Comment by tushar-rishav** [comment]
@AbdealiJK  Sorry got confused. I thought we should move all coala-html related talks to this repo. Anyway feel free to switch back.  :P

**Comment by AbdealiJK** [comment]
@tushar-rishav just a note as you asked on gitter once about package-data

https://github.com/django/django-localflavor/blob/master/setup.py#L37
has a nice function which seems to be cool.
Its MIT so you can copy and give appropriate credit (as they've done at the top of the function)
