### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala-html#4]
We probably want a little circleci script that at least builds the website? Ideally some tests should be run.

@tushar-rishav any experience with that?

**Comment by tushar-rishav** [comment]
@sils1297 Not yet. But yeah sure. I will learn and implement it. :)

**Comment by sils1297** [comment]
maybe @AbdealiJK can give you a few hints

**Comment by AbdealiJK** [comment]
Sure - you can check out the circleci.yml file in coala for a start
@sils1297 you need to enable circleci

**Comment by AbdealiJK** [comment]
Wasn't closed because `master` isnt the default branch. Fixed at https://github.com/coala-analyzer/coala-html/commit/05eedb671df7634d8ce4eae28093e3145828ee4d
