### ISSUE TITLE
Use bower

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala-html#5]
Don't keep static files - rather use bower to manage static dependencies for you

**Comment by tushar-rishav** [comment]
@AbdealiJK Sure. Makes sense. Will do it. :)

**Comment by AbdealiJK** [comment]
Not sure which link you had shown me last time - but it seems github doesnt have bower support. We'd have to push the bower folder to github

**Comment by AbdealiJK** [comment]
Wasn't closed because `master` isnt the default branch. Fixed at https://github.com/coala-analyzer/coala-html/commit/dd1553f3e575e781304ea96965d4ba2f3009397e
