### ISSUE TITLE
Ctrl+C doesn't abort cleanly

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala-html#60]
How am I supposed to stop the server? Best you catch Ctrl+C and clean up. Otherwise I get "Address already in use" repeatedly which is annoying.

**Comment by tushar-rishav** [comment]
Continuing the discussion here.
https://hg.python.org/cpython/file/2.7/Lib/SocketServer.py#l413 shows that they have already exposed the socket object. Maybe we can utilise this to suppress the OSError address in use. 
`socket.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)` and then calling `shutdown` and `close`? Apparently, this approach doesn't work. Not sure why.
CC @Uran198 @AbdealiJK

**Comment by AbdealiJK** [comment]
http://man7.org/linux/man-pages/man7/socket.7.html says:
```
SO_REUSEADDR
              Indicates that the rules used in validating addresses supplied
              in a bind(2) call should allow reuse of local addresses.  For
              AF_INET sockets this means that a socket may bind, except when
              there is an active listening socket bound to the address.
              When the listening socket is bound to INADDR_ANY with a
              specific port then it is not possible to bind to this port for
              any local address.  Argument is an integer boolean flag.
```
So, it seems the listening port is already bound ?

Have you tried http://zaiste.net/2015/06/python_s_simplehttpserver_not_closing_the_port/

**Comment by tushar-rishav** [comment]
@AbdealiJK Oops. They have already done that https://hg.python.org/cpython/file/2.7/Lib/SocketServer.py#l430 
That works like charm :tada: Thanks :D
