### ISSUE TITLE
Highlight lines that produce errors

### ISSUE THREAD

**Issue by tushar-rishav** [coala-analyzer/coala-html#65]
It'd be useful to browse files directly and know the lines that produced errors.

**Comment by sils1297** [comment]
maybe show reults inline?

**Comment by tushar-rishav** [comment]
Um you mean showing the `additional_info` from coala ?

**Comment by tushar-rishav** [comment]
I am thinking of showing the `additional_info` when user hovers over the line number of the highlighted lines. Something that's not blocking the overall browsing. @sils1297

**Comment by sils1297** [comment]
you're speaking of the files view, right? If I show a file it would be neat to see the results directly there?

**Comment by tushar-rishav** [comment]
Yeah. When we open a particular faulty file, we should get info about 
* Why the line produced result. - showing `additional_info`
* How it can be fixed - showing `diffs`

Not sure, maybe showing too much info would look cluttered.
@sils1297

**Comment by sils1297** [comment]
@tushar-rishav make a mockup first? I don't get what you want the additional info for... don't you want to show the result just as before?

**Comment by tushar-rishav** [comment]
@sils1297 coala returns `additional_info` - a brief reason why the results were produced. I am thinking of showing that along with the diff for each highlighted snippet to the user.  Results would be anyway be shown in the results tab.  Anyway sure let me create a mockup first. :+1:

**Comment by sils1297** [comment]
ok but that has nothing to do with the files view right? Maybe offer a button "show additional info" and "show patch"

**Comment by sils1297** [comment]
but first a release!

**Comment by tushar-rishav** [comment]
Alright. :D

**Comment by AbdealiJK** [comment]
This seems to have gone in the direction of https://github.com/coala-analyzer/coala-html/issues/16
If so, please close the older one (As this has more comments) and modify the title of this issue @tushar-rishav
