### ISSUE TITLE
comment from ankit

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala-html#8]
try using lato for sans-serif

**Comment by AbdealiJK** [comment]
I do not understand the current fonts ... We have a lot of them:

```
    font-family: "Helvetica Neue", Helvetica, "Segoe UI", Arial,
                 freesans, sans-serif, "Apple Color Emoji",
                 "Segoe UI Emoji", "Segoe UI Symbol";
```

and 
```
    font-family: Consolas,"Liberation Mono",Menlo,Courier,monospace;
```

Why are there so many ?

**Comment by AbdealiJK** [comment]
CC @tushar-rishav

**Comment by tushar-rishav** [comment]
@AbdealiJK AFAIK sometimes browsers may not support some fonts, in such cases they tend to render the font style which is next in the series. In the worst case the one at the last will be rendered.

**Comment by sils1297** [comment]
I think they are prioritised fallbacks

**Comment by AbdealiJK** [comment]
Fixed in https://github.com/coala-analyzer/coala-html/commit/895b297db7733561e2cf391caf206e7548f03f15
